//! The normalized NPC sub-agent response.
//!
//! The model-facing contract is `{response, beats, claims}`. Private reasoning
//! is taken from the backend thinking channel, not from JSON generated by the
//! model. `speech` / `action` remain derived compatibility fields for older UI
//! and transcript code until those surfaces are moved fully to `beats`.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct NpcBeat {
    /// `speech` or `action`.
    #[serde(default)]
    pub kind: String,
    /// Player-visible beat text.
    #[serde(default)]
    pub text: String,
}

/// Normalized NPC sub-agent response.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct NpcResponse {
    /// The NPC's private reasoning captured from the backend thinking channel.
    #[serde(default)]
    pub reasoning: String,
    /// Organic player-visible text: action and speech may be mixed naturally.
    #[serde(default)]
    pub response: String,
    /// Ordered visible beats for downstream tooling.
    #[serde(default)]
    pub beats: Vec<NpcBeat>,
    /// Derived compatibility speech text.
    #[serde(default)]
    pub speech: String,
    /// Derived compatibility action text.
    #[serde(default)]
    pub action: String,
    /// Discrete claims the NPC asserts (each a non-empty string after coercion).
    #[serde(default)]
    pub claims: Vec<String>,
}
